# See http://www.appveyor.com/docs/appveyor-yml for many more options

# Skip on updates to .md files.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  files:
    - '**/*.md'

install:
  - cinst pester -y

build: off

test_script:
# Test with native PS version
  - ps: . .\Tests\appveyor.pester.ps1 -Test
# Finalize pass - collect and upload results
  - ps: . .\Tests\appveyor.pester.ps1 -Finalize
